server:
  port: 8085

spring:
  application:
    name: alert-processor

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alert-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    mongodb:
      uri: mongodb://localhost:27017/devpulse_alerts

# Optional: SMTP (configure for email notifications)
  mail:
    host: smtp.freesmtpservers.com
    port: 25
    username: testing1234@freesmtpservers.com
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
#            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# Actuator + Prometheus for monitoring
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true

# Prometheus & metric rules config
prometheus:
  base-url: http://localhost:9090

# Path to YAML rule file (relative to classpath or absolute)
metrics:
  rules-file: classpath:metrics-rules.yaml

# WebSocket allowed origin
websocket:
  allowed-origins: "*"